// Package sdk provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package sdk

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AppLog.
const (
	Kafka AppLog = "kafka"
	None  AppLog = "none"
)

// Defines values for EncodedValueEncoding.
const (
	Base64 EncodedValueEncoding = "base64"
	Plain  EncodedValueEncoding = "plain"
	Sha256 EncodedValueEncoding = "sha256"
)

// Defines values for KvDatatype.
const (
	BloomFilter KvDatatype = "bloom_filter"
	Kv          KvDatatype = "kv"
	SortedSet   KvDatatype = "sorted_set"
)

// Defines values for PlanCacheMode.
const (
	N0 PlanCacheMode = 0
	N1 PlanCacheMode = 1
	N2 PlanCacheMode = 2
)

// Defines values for StoreEntryOp.
const (
	Add        StoreEntryOp = "add"
	DelEntries StoreEntryOp = "del_entries"
	DelKey     StoreEntryOp = "del_key"
)

// Defines values for TemplateParamDataType.
const (
	TemplateParamDataTypeBool   TemplateParamDataType = "bool"
	TemplateParamDataTypeDate   TemplateParamDataType = "date"
	TemplateParamDataTypeEnum   TemplateParamDataType = "enum"
	TemplateParamDataTypeJson   TemplateParamDataType = "json"
	TemplateParamDataTypeNumber TemplateParamDataType = "number"
	TemplateParamDataTypeSecret TemplateParamDataType = "secret"
	TemplateParamDataTypeStore  TemplateParamDataType = "store"
	TemplateParamDataTypeString TemplateParamDataType = "string"
	TemplateParamDataTypeTime   TemplateParamDataType = "time"
)

// AdminStats Aggregated FastEdge usage statistics for one group. The group-key fields
// (client_id, app_id, region, country) are present only for the dimensions
// requested in group_by.
type AdminStats struct {
	// AppId Application ID (present when grouped by app)
	AppId *int64 `json:"app_id,omitempty"`

	// ClientId Client ID (present when grouped by client)
	ClientId *int64 `json:"client_id,omitempty"`

	// Country Country (present when grouped by country)
	Country *string `json:"country,omitempty"`

	// ExecTime Execution-time statistics in milliseconds
	ExecTime AdminStatsExecTime `json:"exec_time"`

	// Region Region (present when grouped by region)
	Region *string `json:"region,omitempty"`

	// StatusCounts Request counts by HTTP status class.
	StatusCounts AdminStatsStatusCounts `json:"status_counts"`

	// TotalCount Total number of requests in the group
	TotalCount int64 `json:"total_count"`
}

// AdminStatsExecTime Execution-time statistics in milliseconds
type AdminStatsExecTime struct {
	// Avg Average execution time in ms
	Avg float64 `json:"avg"`

	// Max Max execution time in ms
	Max float64 `json:"max"`

	// Median Median (50th percentile) execution time in ms
	Median float64 `json:"median"`

	// Min Min execution time in ms
	Min float64 `json:"min"`

	// Perc75 75th percentile execution time in ms
	Perc75 float64 `json:"perc75"`

	// Perc90 90th percentile execution time in ms
	Perc90 float64 `json:"perc90"`
}

// AdminStatsStatusCounts Request counts by HTTP status class.
type AdminStatsStatusCounts struct {
	// Count3xx Number of 3xx responses
	Count3xx int64 `json:"count_3xx"`

	// Count4xx Number of 4xx responses
	Count4xx int64 `json:"count_4xx"`

	// Count5xx Number of 5xx responses
	Count5xx int64 `json:"count_5xx"`

	// Success Successful requests: status 0 (for CDN apps) or 2xx
	Success int64 `json:"success"`
}

// App defines model for app.
type App struct {
	// ApiType Wasm API type
	ApiType *string `json:"api_type,omitempty"`

	// Binary ID of the WebAssembly binary to deploy
	Binary *int64 `json:"binary,omitempty"`

	// Comment Optional human-readable description of the application's purpose
	Comment *string `json:"comment,omitempty"`

	// Debug Enable verbose debug logging for 30 minutes. Automatically expires to prevent performance impact.
	Debug *bool `json:"debug,omitempty"`

	// DebugUntil When debugging finishes
	DebugUntil *time.Time `json:"debug_until,omitempty"`

	// Env Environment variables
	Env *map[string]string `json:"env,omitempty"`
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Log *AppLog `json:"log"`

	// Name Unique application name (alphanumeric, hyphens allowed)
	Name *string `json:"name,omitempty"`

	// Networks Networks
	Networks *[]string `json:"networks,omitempty"`

	// Plan Plan name
	Plan *string `json:"plan,omitempty"`

	// PlanId Plan ID
	PlanId *int64 `json:"plan_id,omitempty"`

	// RspHeaders Extra headers to add to the response
	RspHeaders *map[string]string `json:"rsp_headers,omitempty"`

	// Secrets Application secrets
	Secrets *map[string]AppSecretShort `json:"secrets,omitempty"`

	// Status Status code:<br>0 - draft (inactive)<br>1 - enabled<br>2 - disabled<br>5 - suspended
	Status *int `json:"status,omitempty"`

	// Stores Application edge stores
	Stores *map[string]AppStore `json:"stores,omitempty"`

	// Template Template ID
	Template *int64 `json:"template,omitempty"`

	// TemplateName Template name
	TemplateName *string `json:"template_name,omitempty"`

	// Url Auto-generated URL where the application is accessible
	Url *string `json:"url,omitempty"`
}

// AppLog defines model for App.Log.
type AppLog string

// AppSecretShort Application secret short description
type AppSecretShort struct {
	// Comment A description or comment about the secret.
	Comment *string `json:"comment,omitempty"`

	// Id The unique identifier of the secret.
	Id int64 `json:"id"`

	// Name The unique name of the secret.
	Name *string `json:"name,omitempty"`
}

// AppShort defines model for app_short.
type AppShort struct {
	// ApiType Wasm API type
	ApiType string `json:"api_type"`

	// Binary Binary ID
	Binary int64 `json:"binary"`

	// Comment Description of the binary
	Comment *string `json:"comment,omitempty"`

	// Debug Switch on logging for 30 minutes (switched off by default)
	Debug *bool `json:"debug,omitempty"`

	// DebugUntil When debugging finishes
	DebugUntil *time.Time `json:"debug_until,omitempty"`

	// Id App ID
	Id int64 `json:"id"`

	// Name App name
	Name string `json:"name"`

	// Networks Networks
	Networks *[]string `json:"networks,omitempty"`

	// Plan Application plan name
	Plan *string `json:"plan,omitempty"`

	// PlanId Application plan ID
	PlanId int64 `json:"plan_id"`

	// Status Status code:<br>0 - draft (inactive)<br>1 - enabled<br>2 - disabled<br>3 - hourly call limit exceeded<br>4 - daily call limit exceeded<br>5 - suspended
	Status int `json:"status"`

	// Template Template ID
	Template *int64 `json:"template,omitempty"`

	// TemplateName Template name
	TemplateName *string `json:"template_name,omitempty"`

	// UpgradeableTo ID of the binary the app can be upgraded to
	UpgradeableTo *int64 `json:"upgradeable_to,omitempty"`

	// Url App URL
	Url *string `json:"url,omitempty"`
}

// AppShortAdmin defines model for app_short_admin.
type AppShortAdmin struct {
	// Embedded struct due to allOf(#/components/schemas/app_short)
	AppShort `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	// ClientId Client ID
	ClientId int64 `json:"client_id"`

	// ResellerId Reseller ID
	ResellerId *int64 `json:"reseller_id"`
}

// AppStore Application stores
type AppStore struct {
	// Comment A description of the store
	Comment *string `json:"comment,omitempty"`

	// Id The identifier of the store
	Id int64 `json:"id"`

	// Name The name of the store
	Name string `json:"name,omitempty"`
}

// Binary defines model for binary.
type Binary struct {
	// ApiType Wasm API type
	ApiType string `json:"api_type"`

	// Checksum MD5 hash of the binary
	Checksum *string `json:"checksum,omitempty"`

	// Id Binary ID
	Id int64 `json:"id"`

	// Source Source language:<br>0 - unknown<br>1 - Rust<br>2 - JavaScript<br>3 - Go
	Source int `json:"source"`

	// Status Status code:<br>0 - pending<br>1 - compiled<br>2 - compilation failed (errors available)<br>3 - compilation failed (errors not available)<br>4 - resulting binary exceeded the limit<br>5 - unsupported source language
	Status int `json:"status"`

	// UnrefSince Not used since (UTC)
	UnrefSince *string `json:"unref_since,omitempty"`
}

// BinaryShort defines model for binary_short.
type BinaryShort struct {
	// ApiType Wasm API type
	ApiType string `json:"api_type"`

	// Checksum MD5 hash of the binary
	Checksum *string `json:"checksum,omitempty"`

	// Id Binary ID
	Id int64 `json:"id"`

	// Source Source language:<br>0 - unknown<br>1 - Rust<br>2 - JavaScript<br>3 - Go
	Source *int `json:"source,omitempty"`

	// Status Status code:<br>0 - pending<br>1 - compiled<br>2 - compilation failed (errors available)<br>3 - compilation failed (errors not available)<br>4 - resulting binary exceeded the limit<br>5 - unsupported source language
	Status int `json:"status"`

	// UnrefSince Not used since (UTC)
	UnrefSince *string `json:"unref_since,omitempty"`
}

// Byod BYOD (Bring Your Own Data) settings
type Byod struct {
	// Prefix Key prefix to namespace your data within the external store
	Prefix string `json:"prefix"`

	// Url Connection URL for external storage service (Redis, PostgreSQL, etc.)
	Url string `json:"url"`
}

// CallStats Edge app call statistics
type CallStats struct {
	// CountByStatus Count by status
	CountByStatus []CountByStatus `json:"count_by_status"`

	// Time Beginning ot reporting slot
	Time time.Time `json:"time"`
}

// Client defines model for client.
type Client struct {
	// AppCount Actual allowed number of apps
	AppCount int `json:"app_count"`

	// DailyConsumption Actual number of calls for all apps during the current day (UTC)
	DailyConsumption int `json:"daily_consumption"`

	// HourlyConsumption Actual number of calls for all apps during the current hour
	HourlyConsumption int `json:"hourly_consumption"`

	// MonthlyConsumption Actual number of calls for all apps during the current calendar month (UTC)
	MonthlyConsumption int `json:"monthly_consumption"`

	// Networks List of enabled networks
	Networks []Network `json:"networks"`

	// Plan Plan name
	Plan *string `json:"plan,omitempty"`

	// PlanId Plan ID
	PlanId int64 `json:"plan_id"`

	// Status Status code:<br>1 - enabled<br>2 - disabled<br>5 - suspended
	Status int `json:"status"`
}

// ClientUpdate defines model for clientUpdate.
type ClientUpdate struct {
	// Networks List of available networks
	Networks []string `json:"networks"`

	// PlanId Plan ID
	PlanId int64 `json:"plan_id"`
}

// ClientShort defines model for client_short.
type ClientShort struct {
	// Email Client e-mail address
	Email string `json:"email"`

	// Id Client ID
	Id int64 `json:"id"`

	// Name Client name
	Name string `json:"name"`
}

// ConflictError defines model for conflictError.
type ConflictError struct {
	// ConflictingIds List of conflicting entity IDs
	ConflictingIds []int64 `json:"conflicting_ids"`

	// Error Error message
	Error string `json:"error"`
}

// CountByStatus defines model for count_by_status.
type CountByStatus struct {
	// Count Number of app calls
	Count int `json:"count"`

	// Status HTTP status
	Status int `json:"status"`
}

// DurationStats Edge app execution duration statistics
type DurationStats struct {
	// Avg Average duration in usec
	Avg int64 `json:"avg"`

	// Max Max duration in usec
	Max int64 `json:"max"`

	// Median Median (50% percentile) duration in usec
	Median int64 `json:"median"`

	// Min Min duration in usec
	Min int64 `json:"min"`

	// Perc75 75% percentile duration in usec
	Perc75 int64 `json:"perc75"`

	// Perc90 90% percentile duration in usec
	Perc90 int64 `json:"perc90"`

	// Time Beginning of reporting slot
	Time time.Time `json:"time"`
}

// EncodedValue Value with encoding
type EncodedValue struct {
	// Encoding Value encoding method:<br>plain - unencoded text<br>base64 - base64-encoded binary data<br>sha256 - SHA-256 hash (output only), for fields larger than 1024 bytes
	Encoding EncodedValueEncoding `json:"encoding,omitempty"`

	// Value Data value, encoded according to the specified encoding method (see 'encoding' field)
	Value string `json:"value"`
}

// EncodedValueEncoding Value encoding method:<br>plain - unencoded text<br>base64 - base64-encoded binary data<br>sha256 - SHA-256 hash (output only), for fields larger than 1024 bytes
type EncodedValueEncoding string

// Error defines model for error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// Group defines model for group.
type Group struct {
	// DefaultFlag Add new members to the group by default
	DefaultFlag bool `json:"default_flag"`

	// Descr Group description
	Descr *string `json:"descr,omitempty"`

	// Name Group name
	Name string `json:"name"`
}

// GroupShort defines model for group_short.
type GroupShort struct {
	// ClientCount Number of members in the group
	ClientCount *int `json:"client_count,omitempty"`

	// DefaultFlag Add new members to the group by default
	DefaultFlag bool `json:"default_flag"`

	// Descr Group description
	Descr *string `json:"descr,omitempty"`

	// Id Group ID
	Id int64 `json:"id"`

	// Name Group name
	Name string `json:"name"`

	// TemplateCount Number of templates in the group
	TemplateCount *int `json:"template_count,omitempty"`
}

// KvStoreStats defines model for kvStoreStats.
type KvStoreStats struct {
	// DelCount Number of delete operations
	DelCount int64 `json:"del_count"`

	// ReadCount Number of read operations
	ReadCount int64 `json:"read_count"`

	// StorageSize Storage size used over time, in MB*hours
	StorageSize float64 `json:"storage_size"`

	// Time Beginning of reporting slot
	Time *time.Time `json:"time,omitempty"`

	// WriteSize Volume of write operations, in bytes
	WriteSize int64 `json:"write_size"`
}

// KvDatatype Data type of the item
type KvDatatype string

// KvStore defines model for kv_store.
type KvStore struct {
	// AppCount The number of applications that use this store
	AppCount int `json:"app_count"`

	// Byod BYOD (Bring Your Own Data) settings
	Byod *Byod `json:"byod,omitempty"`

	// Comment A description of the store
	Comment *string `json:"comment,omitempty"`

	// Name A name of the store
	Name string `json:"name"`

	// Revision Current store revision (only for non-BYOD stores)
	Revision *int64 `json:"revision,omitempty"`

	// Size Total store size in bytes (zero for BYOD stores)
	Size int64 `json:"size"`

	// UpdatedAt Timestamp of last store revision (only for non-BYOD stores)
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// KvStoreShort defines model for kv_store_short.
type KvStoreShort struct {
	// AppCount The number of applications that use this store
	AppCount int `json:"app_count"`

	// Comment A description of the store
	Comment *string `json:"comment,omitempty"`

	// Id The unique identifier of the store
	Id int64 `json:"id,omitempty"`

	// Name A name of the store
	Name string `json:"name"`

	// Size Total store size in bytes
	Size *int64 `json:"size,omitempty"`
}

// Log defines model for log.
type Log struct {
	// AppName Name of the application that generated this log
	AppName *string `json:"app_name,omitempty"`

	// ClientIp IP address of the client that triggered the log
	ClientIp *string `json:"client_ip,omitempty"`

	// Edge Edge location where the log originated
	Edge *string `json:"edge,omitempty"`

	// Id Unique identifier for this log entry
	Id *string `json:"id,omitempty"`

	// Log The actual log message content
	Log *string `json:"log,omitempty"`

	// RequestId Request ID
	RequestId *string `json:"request_id,omitempty"`

	// Timestamp When the log was generated (RFC3339 format)
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// ModifyStoreDataEntry defines model for modify_store_data_entry.
type ModifyStoreDataEntry struct {
	// Embedded struct due to allOf(#/components/schemas/store_entry)
	StoreEntry `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	// Op Data operation
	Op StoreEntryOp `json:"op"`
}

// Network defines model for network.
type Network struct {
	// IsDefault Is network is default
	IsDefault bool `json:"is_default"`

	// Name Network name
	Name string `json:"name"`
}

// Plan defines model for plan.
type Plan struct {
	// BillingPlanId Billing plan ID
	BillingPlanId *int64 `json:"billing_plan_id,omitempty"`

	// CacheMode Caching mode:<br>0 - no caching<br>1 - client-scoped caching<br>2 - app-scoped caching
	CacheMode PlanCacheMode `json:"cache_mode,omitempty"`

	// Id Plan ID
	Id *int64 `json:"id,omitempty"`

	// MaxDuration Maximum execution time per request in milliseconds. Requests exceeding this limit are terminated.
	MaxDuration int `json:"max_duration"`

	// MaxSubrequests Maximum number of outgoing HTTP requests allowed per invocation (0 disables external requests)
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	MaxSubrequests int `json:"max_subrequests"`

	// MemLimit Maximum memory allocation per instance in bytes. Prevents runaway memory usage.
	MemLimit int `json:"mem_limit"`

	// Name Unique plan identifier (alphanumeric and hyphens)
	Name string `json:"name"`

	// ResellerId Reseller plan ID
	ResellerId int64 `json:"reseller_id"`
}

// PlanCacheMode Caching mode:<br>0 - no caching<br>1 - client-scoped caching<br>2 - app-scoped caching
type PlanCacheMode int

// PrebillingConsumptionData defines model for prebillingConsumptionData.
type PrebillingConsumptionData struct {
	ClientId    *int                `json:"client_id,omitempty"`
	Date        *openapi_types.Date `json:"date,omitempty"`
	MetricName  *string             `json:"metric_name,omitempty"`
	MetricUnit  *string             `json:"metric_unit,omitempty"`
	MetricValue *int                `json:"metric_value,omitempty"`
	Subproduct  *string             `json:"subproduct,omitempty"`
}

// PrebillingConsumptionPagination defines model for prebillingConsumptionPagination.
type PrebillingConsumptionPagination struct {
	CurrentPage *int32 `json:"current_page,omitempty"`
	Limit       *int32 `json:"limit,omitempty"`
	TotalPages  *int32 `json:"total_pages,omitempty"`
}

// PrebillingConsumptionResponse defines model for prebillingConsumptionResponse.
type PrebillingConsumptionResponse struct {
	Data       *[]PrebillingConsumptionData     `json:"data,omitempty"`
	Pagination *PrebillingConsumptionPagination `json:"pagination,omitempty"`
}

// PrebillingMetric defines model for prebillingMetric.
type PrebillingMetric struct {
	// ExecTime Total app execution time, in seconds
	ExecTime *int64 `json:"exec_time,omitempty"`

	// KvDelCount Number of delete operations
	KvDelCount *int64 `json:"kv_del_count,omitempty"`

	// KvReadCount Number of read operations
	KvReadCount *int64 `json:"kv_read_count,omitempty"`

	// KvStorageSize Storage size used over time, in MB*hours
	KvStorageSize *float64 `json:"kv_storage_size,omitempty"`

	// KvWriteSize Volume of write operations, in bytes
	KvWriteSize *int64 `json:"kv_write_size,omitempty"`

	// NumberOfCalls Number of app calls
	NumberOfCalls *int64 `json:"number_of_calls,omitempty"`

	// TotalRuntimeMms Total app execution time, in million milliseconds (1000 seconds) units
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	TotalRuntimeMms *float32 `json:"total_runtime_mms,omitempty"`
}

// PrebillingObject defines model for prebillingObject.
type PrebillingObject struct {
	BillingPlan *string             `json:"billing_plan,omitempty"`
	Client      *int64              `json:"client,omitempty"`
	Date        *openapi_types.Date `json:"date,omitempty"`
	Metrics     PrebillingMetric    `json:"metrics"`
	Region      *string             `json:"region,omitempty"`
}

// PrebillingResponse defines model for prebillingResponse.
type PrebillingResponse = []PrebillingObject

// Secret defines model for secret.
type Secret struct {
	// AppCount The number of applications that use this secret.
	AppCount *int `json:"app_count,omitempty"`

	// Comment A description or comment about the secret.
	Comment *string `json:"comment,omitempty"`

	// Name The unique name of the secret.
	Name *string `json:"name,omitempty"`

	// SecretSlots A list of secret slots associated with this secret.
	SecretSlots *[]SecretSlot `json:"secret_slots,omitempty"`
}

// SecretShort defines model for secret_short.
type SecretShort struct {
	// AppCount The number of applications that use this secret.
	AppCount *int `json:"app_count,omitempty"`

	// Comment A description or comment about the secret.
	Comment *string `json:"comment,omitempty"`

	// Id The unique identifier of the secret.
	Id *int64 `json:"id,omitempty"`

	// Name The unique name of the secret.
	Name string `json:"name"`
}

// SecretSlot defines model for secret_slot.
type SecretSlot struct {
	// Checksum SHA-256 hash of the decrypted value for integrity verification (auto-generated)
	Checksum *string `json:"checksum,omitempty"`

	// Slot Unix timestamp (seconds since epoch) indicating when this secret version becomes active. Use for time-based secret rotation.
	Slot int64 `json:"slot"`

	// Value The plaintext secret value. Will be encrypted with AES-256-GCM before storage.
	Value *string `json:"value,omitempty"`
}

// StoreBloomFilter Bloom filter
type StoreBloomFilter = []EncodedValue

// StoreEntry Edge store entry
type StoreEntry struct {
	// Datatype Data type of the item
	Datatype KvDatatype `json:"datatype"`

	// Key Key of the item
	Key     string              `json:"key"`
	Payload *StoreEntry_Payload `json:"payload,omitempty"`
}

// StoreEntry_Payload defines model for StoreEntry.Payload.
type StoreEntry_Payload struct {
	union json.RawMessage
}

// StoreEntryOp Data operation
type StoreEntryOp string

// StoreEntryShort Edge store entry
type StoreEntryShort struct {
	// Datatype Data type of the item
	Datatype KvDatatype `json:"datatype"`

	// Key Key of the item
	Key string `json:"key"`

	// Payload KV pair value
	Payload *StoreKvPairValue `json:"payload,omitempty"`
}

// StoreKvPairValue defines model for store_kv_pair_value.
type StoreKvPairValue struct {
	// Embedded struct due to allOf(#/components/schemas/encoded_value)
	EncodedValue `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	// Expiry Optional expiration timestamp in RFC3339 format. Entry is automatically deleted after this time.
	Expiry *string `json:"expiry,omitempty"`
}

// StoreSortedSet Sorted set items
type StoreSortedSet = []StoreSortedSetItem

// StoreSortedSetItem defines model for store_sorted_set_item.
type StoreSortedSetItem struct {
	// Embedded struct due to allOf(#/components/schemas/encoded_value)
	EncodedValue `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	// Score Numeric score for sorted set ranking. Lower scores appear first in sorted queries. Not required for delete operations.
	Score *float64 `json:"score,omitempty"`
}

// Template defines model for template.
type Template struct {
	// ApiType Wasm API type
	ApiType *string `json:"api_type,omitempty"`

	// BinaryId ID of the WebAssembly binary to use for this template
	BinaryId int64 `json:"binary_id"`

	// LongDescr Detailed markdown description explaining template features and usage
	LongDescr *string `json:"long_descr,omitempty"`

	// Name Unique name for the template (used for identification and searching)
	Name string `json:"name"`

	// Owned Is the template owned by user?
	Owned bool `json:"owned"`

	// Params Parameters
	Params []TemplateParam `json:"params"`

	// ShortDescr Brief one-line description displayed in template listings
	ShortDescr *string `json:"short_descr,omitempty"`
}

// TemplateParam defines model for template_param.
type TemplateParam struct {
	// DataType Parameter type determines validation and UI rendering:<br>string - text input<br>number - numeric input<br>date - date picker<br>time - time picker<br>secret - references a secret<br>store - references an edge store<br>bool - boolean toggle<br>json - JSON editor or multiline text area with JSON validation<br>enum - dropdown/select with allowed values defined via parameter metadata
	DataType TemplateParamDataType `json:"data_type"`

	// Descr Human-readable explanation of what this parameter controls
	Descr *string `json:"descr,omitempty"`

	// Mandatory If true, this parameter must be provided when instantiating the template
	Mandatory bool `json:"mandatory"`

	// Metadata Optional JSON-encoded string for additional parameter metadata, such as allowed values for enum types
	Metadata *string `json:"metadata,omitempty"`

	// Name Parameter name used as a placeholder in template (e.g., API_KEY, DATABASE_URL)
	Name string `json:"name"`
}

// TemplateParamDataType Parameter type determines validation and UI rendering:<br>string - text input<br>number - numeric input<br>date - date picker<br>time - time picker<br>secret - references a secret<br>store - references an edge store<br>bool - boolean toggle<br>json - JSON editor or multiline text area with JSON validation<br>enum - dropdown/select with allowed values defined via parameter metadata
type TemplateParamDataType string

// TemplateShort defines model for template_short.
type TemplateShort struct {
	// ApiType Wasm API type
	ApiType string `json:"api_type"`

	// Id Template ID
	Id int64 `json:"id"`

	// LongDescr Long description of the template
	LongDescr *string `json:"long_descr,omitempty"`

	// Name Name of the template
	Name string `json:"name"`

	// Owned Is the template owned by user?
	Owned bool `json:"owned"`

	// ShortDescr Short description of the template
	ShortDescr *string `json:"short_descr,omitempty"`
}

// TemplateShortAdmin defines model for template_short_admin.
type TemplateShortAdmin struct {
	// Embedded struct due to allOf(#/components/schemas/template_short)
	TemplateShort `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	// ClientId Client ID
	ClientId int64 `json:"client_id"`

	// Groups Groups the template is shared to
	Groups []int64 `json:"groups"`

	// ResellerId Reseller ID
	ResellerId *int64 `json:"reseller_id"`
}

// AsStoreKvPairValue returns the union data inside the StoreEntry_Payload as a StoreKvPairValue
func (t StoreEntry_Payload) AsStoreKvPairValue() (StoreKvPairValue, error) {
	var body StoreKvPairValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStoreKvPairValue overwrites any union data inside the StoreEntry_Payload as the provided StoreKvPairValue
func (t *StoreEntry_Payload) FromStoreKvPairValue(v StoreKvPairValue) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStoreKvPairValue performs a merge with any union data inside the StoreEntry_Payload, using the provided StoreKvPairValue
func (t *StoreEntry_Payload) MergeStoreKvPairValue(v StoreKvPairValue) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStoreSortedSet returns the union data inside the StoreEntry_Payload as a StoreSortedSet
func (t StoreEntry_Payload) AsStoreSortedSet() (StoreSortedSet, error) {
	var body StoreSortedSet
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStoreSortedSet overwrites any union data inside the StoreEntry_Payload as the provided StoreSortedSet
func (t *StoreEntry_Payload) FromStoreSortedSet(v StoreSortedSet) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStoreSortedSet performs a merge with any union data inside the StoreEntry_Payload, using the provided StoreSortedSet
func (t *StoreEntry_Payload) MergeStoreSortedSet(v StoreSortedSet) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStoreBloomFilter returns the union data inside the StoreEntry_Payload as a StoreBloomFilter
func (t StoreEntry_Payload) AsStoreBloomFilter() (StoreBloomFilter, error) {
	var body StoreBloomFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStoreBloomFilter overwrites any union data inside the StoreEntry_Payload as the provided StoreBloomFilter
func (t *StoreEntry_Payload) FromStoreBloomFilter(v StoreBloomFilter) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStoreBloomFilter performs a merge with any union data inside the StoreEntry_Payload, using the provided StoreBloomFilter
func (t *StoreEntry_Payload) MergeStoreBloomFilter(v StoreBloomFilter) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StoreEntry_Payload) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StoreEntry_Payload) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
